### ISSUE TITLE
"Message too short" error when requesting `SourceData`

### ISSUE THREAD

**Issue by bhagen55** [aws/chrony-candm#5]
I am using this wonderful crate to successfully fetch tracking and source stats info from Chrony, but am running into a snag when trying to fetch `SourceData`.

Specifically, I get this error:
```
Custom { kind: InvalidData, error: DeserializationError(Some("message too short")) }
```

I wanted to drill down a bit more to figure out where this error was coming from, so I copied the `chrony-candm` and `chrony-candm-derive` sources into my repo and pointed my crate to the local copies instead, and somehow the error disappeared and the `SourceData` query began functioning. I am able to replicate this by switching back and forth between a local reference to the `chrony-candm` crate and the usual reference in my `Cargo.toml`.

I would like to try to debug this further myself, but I will need to figure out a way to replicate the issue with the crate checked out in a way so I can modify it. Was hoping to see if anyone had thoughts on why this might be happening while I pursue other methods.

**Comment by jacoblwisniewski** [comment]
Likely the issue you are seeing is due to this issue here https://github.com/aws/chrony-candm/commit/3de36b7f78c88ef41ff829cb708cea99629c7682. Looks like we haven't released that change into a crate release yet. I can look into updating the chrony-candm crate with a v0.1.2 release that includes that fix.

**Comment by bhagen55** [comment]
Ah that would explain why the raw source code works fine while the Cargo release does not!

**Comment by jacoblwisniewski** [comment]
Crate 0.1.2 has been uploaded to crates.io https://crates.io/crates/chrony-candm.
